
export enum AppMode {
  CREATOR = 'CREATOR',
  STUDIO = 'STUDIO',
  INFLUENCER = 'INFLUENCER',
  MOTION = 'MOTION',
  LIVE = 'LIVE',
  GALLERY = 'GALLERY',
  BILLING = 'BILLING',
  DIRECTOR = 'DIRECTOR'
}

export enum GenerationTier {
  SKETCH = 'SKETCH',
  RENDER = 'RENDER'
}

export type Language = 'EN' | 'ES';

export enum Gender { MALE = 'MALE', FEMALE = 'FEMALE' }
export enum Lighting { SOFTBOX = "Softbox", REMBRANDT = "Rembrandt", NEON = "Neon Cyberpunk", WINDOW = "Natural Window", FLASH = "Hard Flash", GOLDEN = "Golden Hour" }
export enum ShotType { CLOSE_UP = "Extreme Close-up", HEADSHOT = "Headshot", WAIST = "Waist Up", FULL = "Full Body", LOW_ANGLE = "Low Angle" }
export enum TimeOfDay { DAWN = "Dawn", NOON = "Noon", GOLDEN = "Golden Hour", BLUE = "Blue Hour", CITY = "City Lights" }
export enum Vibe { NATURAL = "Natural", CINEMATIC = "Cinematic", CYBERPUNK = "Cyberpunk", VINTAGE = "Vintage 90s", PORTRA = "Kodak Portra", MOODY = "Moody" }

export interface UsageStats {
  freeImages: number;
  paidImages: number;
  freeVideos: number;
  paidVideos: number;
  estimatedCost: number;
  totalTokens: number;
  storageUsage?: number;
  storageQuota?: number;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  customInstructions?: string;
  budget?: number;
  createdAt: number;
}

export interface Collection {
    id: string;
    projectId: string;
    name: string;
    createdAt: number;
    icon?: string;
}

export interface ModelMorphology {
    // Biometrics (Granular)
    height: number;      // 0-100 (Maps to cm range)
    bodyFat: number;     // 0-100 (Maps to descriptors: Shredded -> Soft)
    muscleMass: number;  // 0-100 (Maps to hypertrophy)
    boneStructure: number; // 0-100 (Frame size: Petite -> Broad)
    
    // NEW: Body Proportions
    shoulderWidth: number; // 0-100 (Narrow -> Broad)
    legLength: number;     // 0-100 (Short -> Statuesque)
    neckThickness: number; // 0-100 (Thin -> Bull)

    // Dimorphism
    bustChest: number;   // 0-100 (Cup size / Chest breadth)
    hipsWaistRatio: number; // 0-100 (Hourglass / V-Taper intensity)
    
    // Facial Architecture (Cranial)
    faceShape: 'OVAL' | 'SQUARE' | 'HEART' | 'DIAMOND' | 'ROUND';
    foreheadHeight: number; // 0-100 (Low -> High)
    jawlineDefinition: number; // 0-100
    chinProminence: number; // 0-100 (Recessed -> Jutting)
    cheekboneHeight: number;   // 0-100
    
    // Ocular (Eyes)
    eyeSize: number;
    eyeSpacing: number; // 0-100 (Close-set -> Wide-set)
    eyeTilt: number;    // 0-100 (Downturned -> Cat-eye/Upturned)
    eyebrowArch: number; // 0-100 (Flat -> High Arch)
    
    // Nose & Mouth
    noseStructure: number; // 0-100
    lipFullness: number;
    
    // The "Titan" Realism Layer (Pro Dermatology Suite)
    skinTexture: number; // 0-100 (Pore visibility, micro-details)
    skinSheen: number;   // 0-100 (Matte -> Oily/Dewy)
    imperfections: number; // 0-100 (Asymmetry, moles, realism)
    freckleDensity: number; // 0-100 (None -> Heavily Freckled)
    aging: number; // 0-100 (Youth -> Mature)
    grayScale: number; // 0-100 (No Gray -> Salt & Pepper -> White)
    vascularity: number; // 0-100 (Vein visibility)
    redness: number; // 0-100 (Flush / Blood flow / Subsurface)
    pores: number; // 0-100 (High frequency detail)
}

export interface ModelAttributes {
  id: string;
  version: number;
  name: string;
  gender: 'MALE' | 'FEMALE';
  age: number;
  ethnicity: string;
  
  morphology: ModelMorphology;

  skinTone: string;
  eyeColor: string;
  hairStyle: string;
  hairColor: string;
  
  // New Granular Styling
  hairTexture: string; // Straight, Wavy, Curly, Coily
  eyebrowStyle: string; // Plucked, Bushy, Natural
  
  // Styling preferences (ephemeral)
  makeupStyle: string;
  clothingStyle: string;
  
  // New granular styling fields
  glasses: string;
  facialHair: string;
  visualVibe: string;
  
  // Identity markers
  distinctiveFeatures: string; // Tattoos, scars
  
  // CLONE ENGINE
  referenceImage: string | null; // Primary Face
  referenceImages: string[]; // Up to 5 angles
  accessoriesImage: string | null;
  strictness: number; // 0-100 (Identity Locking Strength)
  
  // PROTOCOL: MIMIC-X
  // High-density forensic description generated by Vision API
  syntheticDNA?: string;
  
  // Legacy support
  bodyType?: string;
}

export interface ProPhotoSettings {
  cameraModel: string;
  lensFocalLength: string;
  aperture: string;
  iso: string;
  shutterSpeed: string;
  lightingSetup: string;
  colorGrading: string;
  resolution: string;
  seed?: number;
  customNegative?: string;
}

export interface StudioSettings extends ProPhotoSettings {
  background: string;
  backgroundColor: string;
  shotType: string;
  aspectRatio: string;
  productDescription: string;
  outfitImage: string | null;
  productImage: string | null;
  propPriority: boolean;
  batchSize: number;
  useMagicPrompt: boolean;
  isHighFashion: boolean;
  poseStyle: string;
  editorialVibe: string;
  selectedLocationPreview: string | null;
  lighting: string;
}

export interface InfluencerSettings extends ProPhotoSettings {
  action: string;
  location: string;
  timeOfDay: string;
  cameraAngle: string;
  clothingOverride: string;
  outfitImage: string | null;
  companions: string;
  vibe: string;
  aspectRatio: string;
  useMagicPrompt: boolean;
  selectedLocationPreview: string | null;
}

export interface MotionSettings extends InfluencerSettings {
    fps: string;
    shutterAngle: string;
    stabilization: string;
    cameraType: string;
    lensType: string;
    filmStock: string;
    movement: string;
    customPrompt: string;
    sourceImage: string | null;
}

export interface GeneratedAsset {
  id: string;
  projectId: string;
  collectionId?: string;
  sessionId?: string;
  url: string;     
  blob?: Blob;     
  type: 'IMAGE' | 'VIDEO';
  prompt: string;
  timestamp: number;
  mode: AppMode;
  isMagic: boolean;
  modelId: string;
  usedModel: string;
  keyType: 'FREE' | 'PAID';
  tier: GenerationTier;
  cost: number;
  settings?: StudioSettings | InfluencerSettings | MotionSettings | {};
  tags?: string[];
  isCompressed?: boolean;
}

export interface GenerationResult {
    url: string;
    blob: Blob;
    finalPrompt: string;
    usedModel: string;
    keyType: 'FREE' | 'PAID';
    tier: GenerationTier;
    tags?: string[];
    sessionId?: string;
}

export interface ToastMessage {
  id: string;
  message: string;
  type: 'success' | 'error' | 'info' | 'warning';
}

export interface DirectorShot {
    id: string;
    type: 'STUDIO' | 'INFLUENCER';
    description: string;
    visualDetails: string;
    status: 'PENDING' | 'GENERATING' | 'DONE' | 'FAILED';
    resultAssetId?: string;
    feedback?: string;
}

export interface DirectorPlan {
    campaignName: string;
    modelBrief: Partial<ModelAttributes> & { vibe?: string };
    shots: DirectorShot[];
}

export interface AuditReport {
    score: number;
    analysis: string;
    missingShots: string[];
    consistencyCheck: string;
}

export interface StorageStats {
    usage: number;
    quota: number;
}

export interface Preset {
    id: string;
    name: string;
    mode: 'STUDIO' | 'INFLUENCER' | 'MOTION';
    settings: Partial<StudioSettings | InfluencerSettings | MotionSettings>;
}

export interface ProjectExport {
    version: number;
    project: Project;
    models: ModelAttributes[];
    assets: (Omit<GeneratedAsset, 'blob' | 'url'> & { blobData: string | null })[];
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      [elemName: string]: any;
    }
  }
}
